Repository nextcloud/calendar_resource_management, pull requests merged in 2021-12, with the labels that each got.

#28 Bump NC version to 24
  appinfo/info.xml
Labels: 4. to release

#27 Fix setting entity ID on restriction
  lib/Command/CreateRestriction.php
Labels: 3. to review, bug

#31 Adjust workflows to use `main`
  .github/workflows/csfixer.yml
  .github/workflows/setup.yml
Labels: 3. to review, enhancement, integration

#35 Fix creation of rooms
  lib/Command/CreateRoom.php
Labels: 3. to review, backport-request, bug

#40 Update download instructions
  README.md
Labels: 3. to review, documentation, enhancement

#34 Also print list of stories
  lib/Command/ListResources.php
Labels: 3. to review, enhancement

#43 Update info.xml authors with new maintainers and co-maintainers
  appinfo/info.xml
Labels: 3. to review
