Repository nextcloud/calendar_resource_management, pull requests merged in 2023-01, with the labels that each got.

#74 chore(deps): Drop Nextcloud 23 support (EOL)
  .github/workflows/setup.yml
  appinfo/info.xml
Labels: 3. to review

#76 chore(dev-deps): Bump @nextcloud/coding-standard to 1.0
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
  lib/Migration/Version1000Date20200805220319.php
Labels: 3. to review

#75 chore(deps): Drop PHP7.3 support (EOL)
  .github/workflows/appstore-build-publish.yml
  .github/workflows/csfixer.yml
  .github/workflows/lint.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review

#45 Migrate to new backend registrations
  lib/AppInfo/Application.php
Labels: 4. to release, enhancement, performance

#77 perf(autoloader): Use Composer's authoritative classmap
  composer.json
  composer/autoload.php
Labels: 3. to review, performance

#78 chore(deps): drop PHP 7.4 support
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Command/ListResources.php
  lib/Connector/Resource/Backend.php
  lib/Connector/Resource/ResourceObject.php
  lib/Connector/Resource/Vehicle.php
  lib/Connector/Room/Backend.php
  lib/Connector/Room/Room.php
  lib/Db/AMapper.php
  lib/Db/BuildingMapper.php
  lib/Db/BuildingModel.php
  lib/Db/ResourceMapper.php
  lib/Db/ResourceModel.php
  lib/Db/RestrictionMapper.php
  lib/Db/RestrictionModel.php
  lib/Db/RoomMapper.php
  lib/Db/RoomModel.php
  lib/Db/StoryMapper.php
  lib/Db/StoryModel.php
  lib/Db/VehicleMapper.php
  lib/Db/VehicleModel.php
  lib/Listener/GroupDeletedListener.php
  lib/Listener/UserDeletedListener.php
  lib/Migration/Version1000Date20200805220319.php
  lib/Service/BuildingService.php
  lib/Service/ResourceService.php
  lib/Service/RoomService.php
  lib/Service/VehicleService.php
  tests/Unit/Db/BuildingMapperTest.php
  tests/Unit/Db/ResourceMapperTest.php
  tests/Unit/Db/RestrictionMapperTest.php
  tests/Unit/Db/RoomMapperTest.php
  tests/Unit/Db/StoryMapperTest.php
  tests/Unit/Db/VehicleMapperTest.php
Labels: 3. to review

#79 chore(deps): add PHP 8.2 support
  .github/workflows/setup.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review
