Repository nextcloud/calendar_resource_management, pull requests merged in 2024-05, with the labels that each got.

#125 feat: add support for nextcloud 30
  appinfo/info.xml
Labels: 3. to review, enhancement

#123 chore: reformat info.xml
  appinfo/info.xml
Labels: 3. to review

#127 chore: add renovate.json
  renovate.json
Labels: 3. to review

#122 new CAVEAT on rooms and typo fix
  README.md
Labels: 4. to release

#107 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review, automated, dependencies
